joints:
  shoulder_pan:
    id: 1
    homing_offset: -513
    range_min: 524
    range_max: 3588
    p_coefficient: 16 # may be original 16 is too much, set 12
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  shoulder_lift:
    id: 2
    homing_offset: -14
    range_min: 514
    range_max: 2313
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  elbow_flex:
    id: 3
    homing_offset: 754
    range_min: 2306
    range_max: 3593
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  wrist_flex:
    id: 4
    homing_offset: 243
    range_min: 770
    range_max: 3081
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  wrist_roll:
    id: 5
    homing_offset: 1792
    range_min: 1033
    range_max: 3589
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254

  gripper:
    id: 6
    homing_offset: 1523
    range_min: 525
    range_max: 1283
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
    max_torque_limit: 500
    protection_current: 250
    overload_torque: 25
